package main

import (
	"fmt"
	"sort"
	"strings"
)

// printWidth mirrors .prettierrc.json. The emitter reproduces prettier's
// output directly rather than shelling out to it, so that `go run
// ./cmd/generate` is reproducible without a node toolchain and a prettier
// upgrade cannot silently rewrite the tree. CI runs `prettier --check` as the
// guard that this reproduction stays faithful.
const printWidth = 100

const genHeader = "// Code generated by cmd/generate. DO NOT EDIT."

// tsWriter accumulates a TypeScript source file.
type tsWriter struct {
	b strings.Builder
	// imports is keyed by specifier; each entry holds either a namespace
	// binding or a set of named bindings.
	nsImports    map[string]string
	namedImports map[string]map[string]bool
}

func newTSWriter() *tsWriter {
	return &tsWriter{
		nsImports:    map[string]string{},
		namedImports: map[string]map[string]bool{},
	}
}

func (w *tsWriter) line(s string) {
	w.b.WriteString(s)
	w.b.WriteByte('\n')
}

func (w *tsWriter) blank() { w.b.WriteByte('\n') }

func (w *tsWriter) linef(format string, args ...any) {
	w.line(fmt.Sprintf(format, args...))
}

// importNamespace records `import type * as <binding> from '<spec>'`.
func (w *tsWriter) importNamespace(spec, binding string) {
	w.nsImports[spec] = binding
}

// importNamed records `import type { <name> } from '<spec>'`.
func (w *tsWriter) importNamed(spec, name string) {
	m, ok := w.namedImports[spec]
	if !ok {
		m = map[string]bool{}
		w.namedImports[spec] = m
	}
	m[name] = true
}

// renderImports returns the import block, sorted by specifier. Maps are only
// ever materialised into sorted slices, never iterated directly, so output is
// deterministic.
func (w *tsWriter) renderImports() string {
	specs := make([]string, 0, len(w.nsImports)+len(w.namedImports))
	for s := range w.nsImports {
		specs = append(specs, s)
	}
	for s := range w.namedImports {
		if _, dup := w.nsImports[s]; !dup {
			specs = append(specs, s)
		}
	}
	sort.Strings(specs)

	var b strings.Builder
	for _, s := range specs {
		if binding, ok := w.nsImports[s]; ok {
			fmt.Fprintf(&b, "import type * as %s from %s;\n", binding, quote(s))
			continue
		}
		names := make([]string, 0, len(w.namedImports[s]))
		for n := range w.namedImports[s] {
			names = append(names, n)
		}
		sort.Strings(names)
		fmt.Fprintf(&b, "import type { %s } from %s;\n", strings.Join(names, ", "), quote(s))
	}
	return b.String()
}

// String assembles the final file: header, imports, then body.
func (w *tsWriter) String(sourcePath string) string {
	var b strings.Builder
	b.WriteString(genHeader)
	b.WriteByte('\n')
	if sourcePath != "" {
		fmt.Fprintf(&b, "// Source: %s\n", sourcePath)
	}
	if imports := w.renderImports(); imports != "" {
		b.WriteByte('\n')
		b.WriteString(imports)
	}
	body := w.b.String()
	if body != "" {
		b.WriteByte('\n')
		b.WriteString(body)
	}
	return normalizeTrailing(b.String())
}

// normalizeTrailing strips trailing whitespace from every line and guarantees
// exactly one final newline.
func normalizeTrailing(s string) string {
	lines := strings.Split(s, "\n")
	for i, l := range lines {
		lines[i] = strings.TrimRight(l, " \t")
	}
	out := strings.Join(lines, "\n")
	return strings.TrimRight(out, "\n") + "\n"
}

// jsDoc renders a documentation comment. An empty tag list and empty body
// produce nothing.
//
// Descriptions are never re-wrapped: GOBL's own hard line breaks are preserved
// verbatim, which is both faithful to the source and immune to churn from
// changing a wrap width.
func jsDoc(indent, description string, tags []string) string {
	description = strings.TrimRight(description, " \t\n")
	if description == "" && len(tags) == 0 {
		return ""
	}

	var body []string
	if description != "" {
		body = append(body, strings.Split(escapeDoc(description), "\n")...)
	}
	if len(tags) > 0 {
		if len(body) > 0 {
			body = append(body, "")
		}
		body = append(body, tags...)
	}

	// A single short line with no tags collapses to /** ... */, matching
	// prettier's preferred form.
	if len(body) == 1 {
		oneLine := indent + "/** " + body[0] + " */"
		if len(oneLine) <= printWidth {
			return oneLine + "\n"
		}
	}

	var b strings.Builder
	b.WriteString(indent + "/**\n")
	for _, l := range body {
		if l == "" {
			b.WriteString(indent + " *\n")
		} else {
			b.WriteString(indent + " * " + l + "\n")
		}
	}
	b.WriteString(indent + " */\n")
	return b.String()
}

// escapeDoc neutralises any comment terminator inside documentation text.
func escapeDoc(s string) string {
	return strings.ReplaceAll(s, "*/", "*\\/")
}

// unionDecl renders `export type <name> = A | B;`, breaking to prettier's
// leading-pipe form when the single-line version exceeds the print width.
//
// This is one of only two width computations in the emitter. Hoisting
// property-level enums to named types is what keeps it that way: no union ever
// appears in a property position, where nesting would make width depend on
// context.
func unionDecl(name string, members []string) string {
	joined := strings.Join(members, " | ")

	single := fmt.Sprintf("export type %s = %s;", name, joined)
	if len(single) <= printWidth {
		return single + "\n"
	}

	// Prettier's intermediate form: keep the members together on one indented
	// continuation line before falling back to one per line.
	if cont := "  " + joined + ";"; len(cont) <= printWidth {
		return fmt.Sprintf("export type %s =\n%s\n", name, cont)
	}

	var b strings.Builder
	fmt.Fprintf(&b, "export type %s =\n", name)
	for i, m := range members {
		b.WriteString("  | " + m)
		if i == len(members)-1 {
			b.WriteByte(';')
		}
		b.WriteByte('\n')
	}
	return b.String()
}

// objectEntry renders one `key: value,` line inside an object literal,
// breaking after the colon when the line exceeds the print width. This is the
// emitter's second and last width rule.
func objectEntry(indent, key, value string) string {
	line := indent + key + ": " + value + ","
	if len(line) <= printWidth {
		return line + "\n"
	}
	return indent + key + ":\n" + indent + "  " + value + ",\n"
}

// stringUnion converts raw values into quoted union members.
func stringUnion(values []string) []string {
	out := make([]string, len(values))
	for i, v := range values {
		out[i] = quote(v)
	}
	return out
}

// constDecl renders `export const <name> = <value>;`, breaking after the equals
// sign when the line exceeds the print width.
func constDecl(name, value string) string {
	line := fmt.Sprintf("export const %s = %s;", name, value)
	if len(line) <= printWidth {
		return line + "\n"
	}
	return fmt.Sprintf("export const %s =\n  %s;\n", name, value)
}

// propUnion renders `<key>: <union>;` inside an interface, following the same
// three progressively wider forms prettier uses for a union: one line, then one
// indented continuation line, then one member per line.
func propUnion(indent, key, expr string) string {
	single := indent + key + ": " + expr + ";"
	if len(single) <= printWidth {
		return single + "\n"
	}
	if cont := indent + "  " + expr + ";"; len(cont) <= printWidth {
		return indent + key + ":\n" + cont + "\n"
	}
	var b strings.Builder
	b.WriteString(indent + key + ":\n")
	members := strings.Split(expr, " | ")
	for i, m := range members {
		b.WriteString(indent + "  | " + m)
		if i == len(members)-1 {
			b.WriteByte(';')
		}
		b.WriteByte('\n')
	}
	return b.String()
}
